# -*- coding: utf-8 -*-
"""HCML_Proj_OULAD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzQz1QL-jshC_OoPXKrM0pYmKXbzIKip
"""

# OULAD Temporal Fairness and Explainability Study
!pip -q install pandas numpy scikit-learn matplotlib fairlearn shap xgboost kagglehub

# ============================================================
# 1. Imports and global settings
# ============================================================

import os
import glob
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    roc_auc_score,
    recall_score,
    precision_score,
    confusion_matrix,
)

try:
    from xgboost import XGBClassifier
    XGBOOST_AVAILABLE = True
except Exception:
    XGBOOST_AVAILABLE = False

try:
    import shap
    SHAP_AVAILABLE = True
except Exception:
    SHAP_AVAILABLE = False

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 100)

RANDOM_STATE = 42
MIN_GROUP_SIZE = 50

KEYS = ["code_module", "code_presentation", "id_student"]
SENSITIVE_ATTRS = ["gender", "age_band", "highest_education", "imd_band"]

# ============================================================
# 2. Load OULAD data
# ============================================================
# Expected files:
#   courses.csv
#   assessments.csv
#   studentAssessment.csv
#   studentInfo.csv
#   studentRegistration.csv
#   studentVle.csv
#   vle.csv

REQUIRED_FILES = [
    "courses.csv",
    "assessments.csv",
    "studentAssessment.csv",
    "studentInfo.csv",
    "studentRegistration.csv",
    "studentVle.csv",
    "vle.csv",
]

LOCAL_DATA_DIR = Path("data")
COLAB_DATA_DIR = Path("/content/oulad")
USE_KAGGLEHUB = True


def has_required_oulad_files(path):
    path = Path(path)
    return path.exists() and all((path / name).exists() for name in REQUIRED_FILES)


if has_required_oulad_files(LOCAL_DATA_DIR):
    DATA_DIR = LOCAL_DATA_DIR
    print("Using local data directory:", DATA_DIR.resolve())
elif USE_KAGGLEHUB:
    try:
        import kagglehub
        dataset_path = kagglehub.dataset_download("anlgrbz/student-demographics-online-education-dataoulad")
        DATA_DIR = Path(dataset_path)
        print("Downloaded dataset to:", DATA_DIR)
    except Exception as e:
        print("KaggleHub download failed. Falling back to manual /content/oulad directory.")
        print("Error:", e)
        DATA_DIR = COLAB_DATA_DIR
        DATA_DIR.mkdir(parents=True, exist_ok=True)
else:
    DATA_DIR = COLAB_DATA_DIR
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    print("Using manual data directory:", DATA_DIR)

print("CSV files found:")
for f in glob.glob(str(DATA_DIR / "*.csv")):
    print(" -", f)

def find_file(filename, root_dir):
    """Find a file recursively under root_dir."""
    matches = list(Path(root_dir).rglob(filename))
    if not matches:
        raise FileNotFoundError(
            f"Could not find {filename} under {root_dir}. "
            "Please check whether the OULAD CSV files are uploaded or downloaded correctly."
        )
    return matches[0]


def read_oulad_csv(filename):
    path = find_file(filename, DATA_DIR)
    print(f"Reading {filename} from {path}")
    return pd.read_csv(path)

courses = read_oulad_csv("courses.csv")
assessments = read_oulad_csv("assessments.csv")
student_assess = read_oulad_csv("studentAssessment.csv")
student_info = read_oulad_csv("studentInfo.csv")
student_reg = read_oulad_csv("studentRegistration.csv")
student_vle = read_oulad_csv("studentVle.csv")
vle = read_oulad_csv("vle.csv")

print("\nShapes:")
print("courses:", courses.shape)
print("assessments:", assessments.shape)
print("studentAssessment:", student_assess.shape)
print("studentInfo:", student_info.shape)
print("studentRegistration:", student_reg.shape)
print("studentVle:", student_vle.shape)
print("vle:", vle.shape)

# ============================================================
# 3. Basic inspection
# ============================================================

print("\nstudentInfo columns:")
print(student_info.columns.tolist())

print("\nFinal result distribution:")
print(student_info["final_result"].value_counts(dropna=False))

print("\nSensitive attribute distributions:")
for attr in SENSITIVE_ATTRS:
    print(f"\n{attr}")
    print(student_info[attr].value_counts(dropna=False))

print("\nCourse presentation lengths:")
print(courses.head())

# ============================================================
# 4. Define target and base table
# ============================================================

# Binary target:
#   1 = at-risk / unsuccessful outcome: Withdrawn or Fail
#   0 = successful outcome: Pass or Distinction

target_map = {
    "Withdrawn": 1,
    "Fail": 1,
    "Pass": 0,
    "Distinction": 0,
}

base = student_info.copy()
base["target_unsuccessful"] = base["final_result"].map(target_map)
base = base.dropna(subset=["target_unsuccessful"]).copy()
base["target_unsuccessful"] = base["target_unsuccessful"].astype(int)

# Merge course length for temporal cutoffs.
base = base.merge(
    courses[["code_module", "code_presentation", "module_presentation_length"]],
    on=["code_module", "code_presentation"],
    how="left",
)

print("\nBase table shape:", base.shape)
print("Target distribution:")
print(base["target_unsuccessful"].value_counts(normalize=False))
print(base["target_unsuccessful"].value_counts(normalize=True))

# ============================================================
# 5. Feature engineering
# ============================================================

# Important leakage decision:
#   We do NOT use date_unregistration as a feature because it directly reveals withdrawal.
#   We also do NOT use final_result except as the label.

def aggregate_vle_features(student_vle_df, vle_df, courses_df, fraction):
    """
    Aggregate VLE activity up to a fraction of the course length.

    fraction = 0.25 for early-course features.
    fraction = 1.00 for full-course features.

    We use only dates from 0 to cutoff. Pre-course clicks are excluded by default
    to make the interpretation cleaner.
    """
    sv = student_vle_df.copy()

    sv = sv.merge(
        courses_df[["code_module", "code_presentation", "module_presentation_length"]],
        on=["code_module", "code_presentation"],
        how="left",
    )
    sv["cutoff_date"] = np.floor(sv["module_presentation_length"] * fraction)
    sv = sv[(sv["date"] >= 0) & (sv["date"] <= sv["cutoff_date"])].copy()

    if sv.empty:
        return pd.DataFrame(columns=KEYS)

    # Basic aggregate behavior.
    basic = sv.groupby(KEYS).agg(
        vle_total_clicks=("sum_click", "sum"),
        vle_active_days=("date", "nunique"),
        vle_mean_clicks_per_record=("sum_click", "mean"),
        vle_max_clicks_per_record=("sum_click", "max"),
        vle_num_records=("sum_click", "size"),
    ).reset_index()

    basic["vle_clicks_per_active_day"] = (
        basic["vle_total_clicks"] / basic["vle_active_days"].replace(0, np.nan)
    )

    # Activity-type click features.
    sv2 = sv.merge(
        vle_df[["id_site", "code_module", "code_presentation", "activity_type"]],
        on=["id_site", "code_module", "code_presentation"],
        how="left",
    )

    top_types = sv2["activity_type"].value_counts().head(8).index.tolist()
    sv2["activity_type_limited"] = np.where(
        sv2["activity_type"].isin(top_types),
        sv2["activity_type"],
        "other_activity",
    )

    by_type = sv2.pivot_table(
        index=KEYS,
        columns="activity_type_limited",
        values="sum_click",
        aggfunc="sum",
        fill_value=0,
    ).reset_index()

    by_type.columns = [
        c if c in KEYS else f"clicks_{str(c)}"
        for c in by_type.columns
    ]

    out = basic.merge(by_type, on=KEYS, how="left")
    return out

def aggregate_assessment_features(student_assessment_df, assessments_df, courses_df, fraction):
    """
    Aggregate assessment behavior available up to a fraction of course length.

    Only submissions observed on or before the temporal cutoff are used. This
    applies to the full-course setting too, because late submissions after the
    module presentation length would otherwise leak future course information.
    """
    sa = student_assessment_df.copy()
    ass = assessments_df.copy()

    sa = sa.merge(
        ass[["id_assessment", "code_module", "code_presentation", "assessment_type", "date", "weight"]],
        on="id_assessment",
        how="left",
    )

    sa = sa.merge(
        courses_df[["code_module", "code_presentation", "module_presentation_length"]],
        on=["code_module", "code_presentation"],
        how="left",
    )

    sa["cutoff_date"] = np.floor(sa["module_presentation_length"] * fraction)

    # Prevent data leakage: only use submissions actually observed before the cutoff.
    sa = sa[(sa["date_submitted"].notna()) & (sa["date_submitted"] <= sa["cutoff_date"])].copy()

    if sa.empty:
        return pd.DataFrame(columns=KEYS)

    sa["weighted_score"] = sa["score"] * sa["weight"] / 100.0
    sa["late_submission"] = np.where(
        sa["date"].notna(),
        (sa["date_submitted"] > sa["date"]).astype(float),
        np.nan,
    )
    sa["days_submitted_before_due"] = np.where(
        sa["date"].notna(),
        sa["date"] - sa["date_submitted"],
        np.nan,
    )

    agg = sa.groupby(KEYS).agg(
        assess_num_submitted=("id_assessment", "count"),
        assess_mean_score=("score", "mean"),
        assess_min_score=("score", "min"),
        assess_max_score=("score", "max"),
        assess_weighted_score_sum=("weighted_score", "sum"),
        assess_total_weight_seen=("weight", "sum"),
        assess_late_rate=("late_submission", "mean"),
        assess_mean_days_before_due=("days_submitted_before_due", "mean"),
    ).reset_index()

    return agg

def registration_features(student_reg_df):
    """
    Registration features that should be available before/during the course.
    date_unregistration is deliberately excluded to avoid leakage.
    """
    reg = student_reg_df[KEYS + ["date_registration"]].copy()
    reg["registered_before_start"] = (reg["date_registration"] < 0).astype(float)
    reg["days_registered_before_start"] = -reg["date_registration"]
    return reg

def build_dataset_for_stage(fraction, stage_name):
    """Build modeling table for one temporal stage."""
    print(f"\nBuilding dataset for {stage_name}, fraction={fraction}")

    vle_feats = aggregate_vle_features(student_vle, vle, courses, fraction)
    ass_feats = aggregate_assessment_features(student_assess, assessments, courses, fraction)
    reg_feats = registration_features(student_reg)

    print("VLE features:", vle_feats.shape)
    print("Assessment features:", ass_feats.shape)
    print("Registration features:", reg_feats.shape)

    df = base.copy()
    df = df.merge(reg_feats, on=KEYS, how="left")
    df = df.merge(vle_feats, on=KEYS, how="left")
    df = df.merge(ass_feats, on=KEYS, how="left")

    candidate_cols = KEYS + [
      "target_unsuccessful",
      "module_presentation_length",
      "gender",
      "age_band",
      "highest_education",
      "imd_band",
      "region",
      "num_of_prev_attempts",
      "studied_credits",
      "date_registration",
      "registered_before_start",
      "days_registered_before_start",
    ]

    engineered_cols = [
        c for c in df.columns
        if c.startswith("vle_") or c.startswith("clicks_") or c.startswith("assess_")
    ]

    keep_cols = [c for c in candidate_cols if c in df.columns] + engineered_cols
    keep_cols = list(dict.fromkeys(keep_cols))
    out = df[keep_cols].copy()

    # Students with no observed activity/submission by the cutoff should represent
    # zero observed behavior, not a median-imputed typical student.
    for c in engineered_cols:
        if c in out.columns:
            out[c] = out[c].fillna(0)

    out["stage"] = stage_name
    print("Final stage table:", out.shape)
    return out

early_df = build_dataset_for_stage(0.25, "early_25pct")
full_df = build_dataset_for_stage(1.00, "full_100pct")

print("\nEarly dataset head:")
display(early_df.head())

print("\nFull dataset head:")
display(full_df.head())

# ============================================================
# 6. Train/test split
# ============================================================
# Use the same held-out students for early and full models.
# FIX: Split by unique id_student to prevent data leakage across train/test sets.

unique_students = base.groupby("id_student", as_index=False)["target_unsuccessful"].max()
train_students, test_students = train_test_split(
    unique_students[["id_student"]],
    test_size=0.25,
    random_state=RANDOM_STATE,
    stratify=unique_students["target_unsuccessful"],
)

def apply_split(df):
    train = df.merge(train_students, on="id_student", how="inner")
    test = df.merge(test_students, on="id_student", how="inner")
    return train, test

early_train, early_test = apply_split(early_df)
full_train, full_test = apply_split(full_df)

print("\nSplit sizes:")
print("early train/test:", early_train.shape, early_test.shape)
print("full train/test:", full_train.shape, full_test.shape)

# ============================================================
# 7. Preprocessing and model training
# ============================================================

DROP_COLS = KEYS + ["target_unsuccessful", "stage"]


def get_xy(df):
    y = df["target_unsuccessful"].astype(int)
    X = df.drop(columns=DROP_COLS, errors="ignore")
    return X, y


def make_preprocessor(X):
    categorical_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()
    numeric_cols = [c for c in X.columns if c not in categorical_cols]

    numeric_pipe = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ])

    categorical_pipe = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore")),
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_pipe, numeric_cols),
            ("cat", categorical_pipe, categorical_cols),
        ],
        remainder="drop",
    )

    return preprocessor, numeric_cols, categorical_cols

def build_models(X_train):
    models = {
        "LogisticRegression": LogisticRegression(
            max_iter=1000,
            class_weight="balanced",
            random_state=RANDOM_STATE,
        ),
        "RandomForest": RandomForestClassifier(
            n_estimators=250,
            min_samples_leaf=5,
            class_weight="balanced_subsample",
            n_jobs=-1,
            random_state=RANDOM_STATE,
        ),
    }

    if XGBOOST_AVAILABLE:
        # Detect if GPU is available via nvidia-smi
        import subprocess
        try:
            subprocess.check_output('nvidia-smi')
            tree_method = 'hist'
            device = 'cuda'
            print("GPU detected! XGBoost will use GPU acceleration.")
        except Exception:
            tree_method = 'auto'
            device = 'cpu'

        models["XGBoost"] = XGBClassifier(
            n_estimators=250,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            eval_metric="logloss",
            random_state=RANDOM_STATE,
            tree_method=tree_method,
            device=device,
        )

    pipelines = {
        name: Pipeline(steps=[("prep", make_preprocessor(X_train)[0]), ("model", model)])
        for name, model in models.items()
    }
    return pipelines

def evaluate_predictions(y_true, y_pred, y_prob=None):
    out = {
        "accuracy": accuracy_score(y_true, y_pred),
        "balanced_accuracy": balanced_accuracy_score(y_true, y_pred),
        "precision_at_risk": precision_score(y_true, y_pred, zero_division=0),
        "recall_at_risk": recall_score(y_true, y_pred, zero_division=0),
        "f1_at_risk": f1_score(y_true, y_pred, zero_division=0),
    }
    if y_prob is not None:
        try:
            out["roc_auc"] = roc_auc_score(y_true, y_prob)
        except Exception:
            out["roc_auc"] = np.nan
    else:
        out["roc_auc"] = np.nan
    return out

def fit_and_evaluate_stage(stage_name, train_df, test_df):
    X_train, y_train = get_xy(train_df)
    X_test, y_test = get_xy(test_df)

    pipelines = build_models(X_train)
    fitted = {}
    rows = []

    for model_name, pipe in pipelines.items():
        print(f"Training {model_name} for {stage_name}...")
        pipe.fit(X_train, y_train)

        y_pred = pipe.predict(X_test)
        y_prob = pipe.predict_proba(X_test)[:, 1] if hasattr(pipe, "predict_proba") else None

        metrics = evaluate_predictions(y_test, y_pred, y_prob)
        metrics["stage"] = stage_name
        metrics["model"] = model_name
        rows.append(metrics)
        fitted[model_name] = pipe

    return pd.DataFrame(rows), fitted


perf_early, models_early = fit_and_evaluate_stage("early_25pct", early_train, early_test)
perf_full, models_full = fit_and_evaluate_stage("full_100pct", full_train, full_test)

performance_table = pd.concat([perf_early, perf_full], ignore_index=True)
performance_table = performance_table[[
    "stage", "model", "accuracy", "balanced_accuracy", "precision_at_risk",
    "recall_at_risk", "f1_at_risk", "roc_auc"
]]

print("\nOverall predictive performance:")
display(performance_table.sort_values(["model", "stage"]))

# ============================================================
# 8. Fairness and subgroup metrics
# ============================================================

def safe_confusion_metrics(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    tpr = tp / (tp + fn) if (tp + fn) > 0 else np.nan
    fpr = fp / (fp + tn) if (fp + tn) > 0 else np.nan
    fnr = fn / (fn + tp) if (fn + tp) > 0 else np.nan
    tnr = tn / (tn + fp) if (tn + fp) > 0 else np.nan
    selection_rate = np.mean(y_pred)
    return {
        "tp": tp,
        "tn": tn,
        "fp": fp,
        "fn": fn,
        "tpr_recall_at_risk": tpr,
        "fpr": fpr,
        "fnr": fnr,
        "tnr": tnr,
        "selection_rate_pred_at_risk": selection_rate,
    }

def subgroup_metric_table(test_df, fitted_model, sensitive_attr, stage_name, model_name, min_group_size=MIN_GROUP_SIZE):
    X_test, y_true = get_xy(test_df)
    y_pred = fitted_model.predict(X_test)
    y_prob = fitted_model.predict_proba(X_test)[:, 1] if hasattr(fitted_model, "predict_proba") else np.full(len(y_true), np.nan)

    tmp = test_df[[sensitive_attr]].copy()
    tmp["y_true"] = np.asarray(y_true)
    tmp["y_pred"] = np.asarray(y_pred)
    tmp["y_prob"] = np.asarray(y_prob)

    rows = []
    for group_value, g in tmp.groupby(sensitive_attr, dropna=False):
        if len(g) < min_group_size:
            continue

        cm = safe_confusion_metrics(g["y_true"], g["y_pred"])
        row = {
            "stage": stage_name,
            "model": model_name,
            "sensitive_attr": sensitive_attr,
            "group": str(group_value),
            "n": len(g),
            "base_rate_true_at_risk": g["y_true"].mean(),
            "accuracy": accuracy_score(g["y_true"], g["y_pred"]),
            "balanced_accuracy": balanced_accuracy_score(g["y_true"], g["y_pred"]),
            "precision_at_risk": precision_score(g["y_true"], g["y_pred"], zero_division=0),
            "recall_at_risk": recall_score(g["y_true"], g["y_pred"], zero_division=0),
            "f1_at_risk": f1_score(g["y_true"], g["y_pred"], zero_division=0),
        }
        row.update(cm)

        try:
            row["roc_auc"] = roc_auc_score(g["y_true"], g["y_prob"])
        except Exception:
            row["roc_auc"] = np.nan

        rows.append(row)

    return pd.DataFrame(rows)

def fairness_gap_summary(subgroup_df):
    """
    Summarise group gaps for each stage-model-sensitive attribute combination.
    Difference is max group metric - min group metric.
    """
    metrics_for_gap = [
        "selection_rate_pred_at_risk",
        "tpr_recall_at_risk",
        "fpr",
        "fnr",
        "accuracy",
        "balanced_accuracy",
        "f1_at_risk",
        "roc_auc",
    ]

    rows = []
    group_cols = ["stage", "model", "sensitive_attr"]
    for keys_, g in subgroup_df.groupby(group_cols):
        row = dict(zip(group_cols, keys_))
        row["num_groups_included"] = g["group"].nunique()
        row["min_group_size"] = g["n"].min()
        row["max_group_size"] = g["n"].max()

        for m in metrics_for_gap:
            values = g[m].dropna()
            if len(values) >= 2:
                row[f"{m}_gap"] = values.max() - values.min()
                row[f"{m}_min"] = values.min()
                row[f"{m}_max"] = values.max()
            else:
                row[f"{m}_gap"] = np.nan
                row[f"{m}_min"] = np.nan
                row[f"{m}_max"] = np.nan
        rows.append(row)

    return pd.DataFrame(rows)

def run_fairness_analysis(stage_name, test_df, fitted_models):
    all_rows = []
    for model_name, model in fitted_models.items():
        for attr in SENSITIVE_ATTRS:
            table = subgroup_metric_table(test_df, model, attr, stage_name, model_name)
            all_rows.append(table)
    return pd.concat(all_rows, ignore_index=True)


subgroup_early = run_fairness_analysis("early_25pct", early_test, models_early)
subgroup_full = run_fairness_analysis("full_100pct", full_test, models_full)

subgroup_metrics = pd.concat([subgroup_early, subgroup_full], ignore_index=True)
fairness_gaps = fairness_gap_summary(subgroup_metrics)

print("\nSubgroup metrics:")
display(subgroup_metrics.head(30))

print("\nFairness gap summary:")
display(fairness_gaps.sort_values(["model", "sensitive_attr", "stage"]))

# ============================================================
# 9. Plots
# ============================================================

OUTPUT_DIR = Path("/content/oulad_outputs") if Path("/content").exists() else Path("oulad_outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def save_bar_plot(df, x, y, hue, title, filename, rotation=45):
    plt.figure(figsize=(10, 5))
    groups = df[hue].unique().tolist()
    x_values = df[x].unique().tolist()

    width = 0.8 / max(len(groups), 1)
    positions = np.arange(len(x_values))

    for i, group in enumerate(groups):
        sub = df[df[hue] == group].set_index(x).reindex(x_values)
        plt.bar(positions + i * width, sub[y].values, width=width, label=str(group))

    plt.xticks(positions + width * (len(groups) - 1) / 2, x_values, rotation=rotation, ha="right")
    plt.ylabel(y)
    plt.title(title)
    plt.legend(title=hue, bbox_to_anchor=(1.05, 1), loc="upper left")
    plt.tight_layout()
    path = OUTPUT_DIR / filename
    plt.savefig(path, dpi=200, bbox_inches="tight")
    plt.show()
    print("Saved:", path)


plt.figure(figsize=(9, 5))
for model_name, g in performance_table.groupby("model"):
    stage_order = {"early_25pct": 0, "full_100pct": 1}
    g_sorted = g.assign(stage_order=g["stage"].map(stage_order)).sort_values("stage_order")
    plt.plot(g_sorted["stage"], g_sorted["balanced_accuracy"], marker="o", label=model_name)
plt.title("Overall balanced accuracy: early vs full course")
plt.ylabel("Balanced accuracy")
plt.xlabel("Stage")
plt.legend()
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "overall_balanced_accuracy_by_stage.png", dpi=200)
plt.show()

for model_name in fairness_gaps["model"].unique():
    plot_df = fairness_gaps[fairness_gaps["model"] == model_name].copy()
    save_bar_plot(
        plot_df,
        x="sensitive_attr",
        y="fnr_gap",
        hue="stage",
        title=f"False negative rate gap by sensitive attribute: {model_name}",
        filename=f"fnr_gap_{model_name}.png",
    )

    save_bar_plot(
        plot_df,
        x="sensitive_attr",
        y="selection_rate_pred_at_risk_gap",
        hue="stage",
        title=f"Predicted at-risk selection rate gap: {model_name}",
        filename=f"selection_rate_gap_{model_name}.png",
    )

# ============================================================
# 10. Detailed subgroup inspection for chosen model
# ============================================================
CHOSEN_MODEL = "RandomForest" if "RandomForest" in models_early else list(models_early.keys())[0]
print("Chosen model for detailed subgroup inspection:", CHOSEN_MODEL)

detail = subgroup_metrics[subgroup_metrics["model"] == CHOSEN_MODEL].copy()
detail_sorted = detail.sort_values(["sensitive_attr", "stage", "fnr"], ascending=[True, True, False])
display(detail_sorted[[
    "stage", "sensitive_attr", "group", "n", "base_rate_true_at_risk",
    "selection_rate_pred_at_risk", "recall_at_risk", "fnr", "fpr",
    "balanced_accuracy", "roc_auc"
]])

# ============================================================
# 11. Feature names and feature importance
# ============================================================
def get_feature_names_from_pipeline(pipe):
    prep = pipe.named_steps["prep"]
    feature_names = []

    for name, transformer, cols in prep.transformers_:
        if name == "remainder" and transformer == "drop":
            continue
        if hasattr(transformer, "named_steps") and "onehot" in transformer.named_steps:
            ohe = transformer.named_steps["onehot"]
            names = ohe.get_feature_names_out(cols)
            feature_names.extend(names.tolist())
        else:
            feature_names.extend(cols)

    return np.array(feature_names)

from google.colab import drive
drive.mount('/content/drive')

def model_feature_importance(pipe, top_n=25):
    feature_names = get_feature_names_from_pipeline(pipe)
    model = pipe.named_steps["model"]

    if hasattr(model, "feature_importances_"):
        importances = model.feature_importances_
    elif hasattr(model, "coef_"):
        importances = np.abs(model.coef_[0])
    else:
        return None

    imp = pd.DataFrame({
        "feature": feature_names,
        "importance": importances,
    }).sort_values("importance", ascending=False)

    return imp.head(top_n)

for stage_name, fitted_models in [
    ("early_25pct", models_early),
    ("full_100pct", models_full),
]:
    if CHOSEN_MODEL in fitted_models:
        imp = model_feature_importance(fitted_models[CHOSEN_MODEL], top_n=25)
        print(f"\nTop feature importance: {stage_name}, {CHOSEN_MODEL}")
        display(imp)

        if imp is not None:
            plt.figure(figsize=(8, 7))
            plt.barh(imp["feature"][::-1], imp["importance"][::-1])
            plt.title(f"Top features: {stage_name}, {CHOSEN_MODEL}")
            plt.xlabel("Importance")
            plt.tight_layout()
            plt.savefig(OUTPUT_DIR / f"feature_importance_{stage_name}_{CHOSEN_MODEL}.png", dpi=200, bbox_inches="tight")
            plt.show()

# ============================================================
# 12. SHAP analysis
# ============================================================
# This part can be slow.

RUN_SHAP = True
SHAP_SAMPLE_SIZE = 800


def run_shap_for_tree_model(pipe, test_df, stage_name, model_name, sample_size=800):
    if not SHAP_AVAILABLE:
        print("SHAP is not available.")
        return None

    model = pipe.named_steps["model"]
    if not hasattr(model, "feature_importances_"):
        print(f"Skipping SHAP for {model_name}: model is not tree-based.")
        return None

    X_test_raw, _ = get_xy(test_df)
    n = min(sample_size, len(X_test_raw))
    X_sample_raw = X_test_raw.sample(n=n, random_state=RANDOM_STATE)

    prep = pipe.named_steps["prep"]
    X_sample_trans = prep.transform(X_sample_raw)
    feature_names = get_feature_names_from_pipeline(pipe)

    if hasattr(X_sample_trans, "toarray"):
        X_sample_trans_dense = X_sample_trans.toarray()
    else:
        X_sample_trans_dense = X_sample_trans

    print(f"Running SHAP for {stage_name}, {model_name}, sample size={n}")

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_sample_trans_dense)

    if isinstance(shap_values, list):
        shap_positive = shap_values[1]
    else:
        shap_positive = shap_values
        if len(shap_positive.shape) == 3:
            shap_positive = shap_positive[:, :, 1]

    shap_df = pd.DataFrame(shap_positive, columns=feature_names)
    mean_abs = shap_df.abs().mean().sort_values(ascending=False).reset_index()
    mean_abs.columns = ["feature", "mean_abs_shap"]

    top = mean_abs.head(25)
    plt.figure(figsize=(8, 7))
    plt.barh(top["feature"][::-1], top["mean_abs_shap"][::-1])
    plt.title(f"Mean absolute SHAP values: {stage_name}, {model_name}")
    plt.xlabel("Mean |SHAP value|")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"shap_mean_abs_{stage_name}_{model_name}.png", dpi=200, bbox_inches="tight")
    plt.show()

    try:
        shap.summary_plot(
            shap_positive,
            X_sample_trans_dense,
            feature_names=feature_names,
            show=False,
            max_display=25,
        )
        plt.title(f"SHAP summary: {stage_name}, {model_name}")
        plt.tight_layout()
        plt.savefig(OUTPUT_DIR / f"shap_summary_{stage_name}_{model_name}.png", dpi=200, bbox_inches="tight")
        plt.show()
    except Exception as e:
        print("Could not create SHAP summary plot:", e)

    return mean_abs


if RUN_SHAP:
    shap_results = []
    models_to_analyze = ["RandomForest", "XGBoost"]

    for m_name in models_to_analyze:
        if m_name in models_early and m_name in models_full:
            print(f"\n--- Analyzing SHAP for {m_name} ---")
            shap_early = run_shap_for_tree_model(
                models_early[m_name], early_test,
                "early_25pct", m_name, SHAP_SAMPLE_SIZE
            )
            shap_full = run_shap_for_tree_model(
                models_full[m_name], full_test,
                "full_100pct", m_name, SHAP_SAMPLE_SIZE
            )

            if shap_early is not None and shap_full is not None:
                shap_early["stage"] = "early_25pct"
                shap_early["model"] = m_name
                shap_full["stage"] = "full_100pct"
                shap_full["model"] = m_name
                shap_results.extend([shap_early, shap_full])
        else:
            print(f"Model {m_name} not found in trained models.")

    if shap_results:
        shap_compare = pd.concat(shap_results, ignore_index=True)
        print("\nSHAP comparison top features:")
        display(shap_compare.groupby(["model", "stage"]).head(10))
        shap_compare.to_csv(OUTPUT_DIR / "shap_mean_abs_comparison.csv", index=False)
else:
    print("Skipping SHAP analysis.")

# ============================================================
# 13. Feature-family importance
# ============================================================
# This gives a clean report-level explanation of whether the model relies more on demographics, VLE engagement, assessments, registration, etc.


def broad_feature_family(feature_name):
    f = str(feature_name)
    if f.startswith("vle_") or f.startswith("clicks_"):
        return "VLE engagement"
    if f.startswith("assess_"):
        return "Assessment"
    if "gender" in f or "age_band" in f or "highest_education" in f or "imd_band" in f:
        return "Demographic"
    if "code_module" in f or "code_presentation" in f:
        return "Course context"
    if "region" in f:
        return "Region"
    if "registration" in f or "registered" in f:
        return "Registration"
    if "num_of_prev_attempts" in f or "studied_credits" in f:
        return "Prior study profile"
    return "Other"

def aggregate_importance_by_family(importance_df):
    if importance_df is None:
        return None
    tmp = importance_df.copy()
    tmp["family"] = tmp["feature"].apply(broad_feature_family)
    return tmp.groupby("family", as_index=False)["importance"].sum().sort_values("importance", ascending=False)

family_rows = []
for stage_name, fitted_models in [
    ("early_25pct", models_early),
    ("full_100pct", models_full),
]:
    if CHOSEN_MODEL in fitted_models:
        imp_all = model_feature_importance(fitted_models[CHOSEN_MODEL], top_n=100000)
        fam = aggregate_importance_by_family(imp_all)
        if fam is not None:
            fam["stage"] = stage_name
            fam["model"] = CHOSEN_MODEL
            family_rows.append(fam)

if family_rows:
    family_importance = pd.concat(family_rows, ignore_index=True)
    print("\nFeature-family importance:")
    display(family_importance)

    plt.figure(figsize=(9, 5))
    families = family_importance["family"].unique().tolist()
    stages = ["early_25pct", "full_100pct"]
    x = np.arange(len(families))
    width = 0.8 / len(stages)

    for i, stage in enumerate(stages):
        sub = family_importance[family_importance["stage"] == stage].set_index("family").reindex(families).fillna(0)
        plt.bar(x + i * width, sub["importance"].values, width=width, label=stage)

    plt.xticks(x + width * (len(stages) - 1) / 2, families, rotation=45, ha="right")
    plt.ylabel("Summed feature importance")
    plt.title(f"Feature-family importance: {CHOSEN_MODEL}")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"feature_family_importance_{CHOSEN_MODEL}.png", dpi=200, bbox_inches="tight")
    plt.show()

# ============================================================
# 14. Export tables for report
# ============================================================

performance_table.to_csv(OUTPUT_DIR / "overall_performance.csv", index=False)
subgroup_metrics.to_csv(OUTPUT_DIR / "subgroup_metrics.csv", index=False)
fairness_gaps.to_csv(OUTPUT_DIR / "fairness_gaps.csv", index=False)

if "family_importance" in globals():
    family_importance.to_csv(OUTPUT_DIR / "feature_family_importance.csv", index=False)

print("\nSaved output files to:", OUTPUT_DIR)
for p in OUTPUT_DIR.glob("*"):
    print(" -", p)

display(
    fairness_gaps.sort_values(
        ["model", "sensitive_attr", "stage"]
    )
)

display(
    subgroup_metrics[
        subgroup_metrics["model"].isin(["RandomForest", "XGBoost"])
    ].sort_values(
        ["model", "sensitive_attr", "stage", "fnr"],
        ascending=[True, True, True, False]
    )[[
        "stage", "model", "sensitive_attr", "group", "n",
        "base_rate_true_at_risk",
        "selection_rate_pred_at_risk",
        "recall_at_risk",
        "fnr",
        "fpr",
        "balanced_accuracy",
        "roc_auc"
    ]]
)

display(performance_table.sort_values(["model", "stage"]))

"""### Refined Fairness Metrics Analysis
Incorporating the logic for data leakage prevention and missing value handling, the following section provides a rigorous comparison of evaluation metrics. The analysis focuses on the following dimensions:

1. **Base Rate vs. Predicted Rate**: Observes whether the model overestimates risk for specific vulnerable groups (predicted proportion significantly higher than the true proportion) or is overly optimistic regarding advantaged groups.
2. **False Negative Rate (FNR)**: For an early-warning system, FNR is the most critical fairness metric. A higher FNR indicates that a larger number of high-risk students in a given group are missed by the model, depriving them of timely intervention resources.
3. **Temporal Mitigation**: Compares the `early_25pct` and `full_100pct` stages to evaluate whether the FNR disparities (gaps) between groups narrow as the course progresses (i.e., as more behavioral data and assessment scores are introduced).
"""

# Extract core fairness metrics for RandomForest across Highest Education and IMD Band
focus_attrs = ['highest_education', 'imd_band']

if 'subgroup_metrics' in globals():
    for attr in focus_attrs:
        print(f"\n{'='*60}")
        print(f"Fairness Analysis for: {attr} (Model: RandomForest)")
        print(f"{'='*60}")

        df_sub = subgroup_metrics[(subgroup_metrics['model'] == 'RandomForest') &
                                  (subgroup_metrics['sensitive_attr'] == attr)]

        # Compare early and full stages using a pivot table
        pivot = df_sub.pivot(
            index='group',
            columns='stage',
            values=['base_rate_true_at_risk', 'fnr', 'selection_rate_pred_at_risk', 'recall_at_risk']
        )

        # Flatten column names
        pivot.columns = [f"{c[0]}_{c[1]}" for c in pivot.columns]

        # Sort descending by true risk rate in the early stage
        pivot = pivot.sort_values("base_rate_true_at_risk_early_25pct", ascending=False)

        # Select core columns to display
        cols_to_show = [
            'base_rate_true_at_risk_early_25pct',
            'selection_rate_pred_at_risk_early_25pct',
            'fnr_early_25pct',
            'fnr_full_100pct'
        ]

        display_df = pivot[cols_to_show].copy()
        display_df.columns = [
            'True At-Risk Rate',
            'Predicted At-Risk Rate (Early)',
            'FNR (Early 25%)',
            'FNR (Full 100%)'
        ]

        display(display_df.round(3))

        # Calculate FNR Gap
        early_gap = display_df['FNR (Early 25%)'].max() - display_df['FNR (Early 25%)'].min()
        full_gap = display_df['FNR (Full 100%)'].max() - display_df['FNR (Full 100%)'].min()
        print(f"-> FNR Gap (Early 25%): {early_gap:.3f}")
        print(f"-> FNR Gap (Full 100%): {full_gap:.3f}\n")
else:
    print("The preceding cells (specifically fairness metrics computation) must be executed before running this analysis.")

"""### Subgroup XAI: Feature Importance Differences Between Groups
To directly address the feedback: *"Do you plan to calculate the differences in feature importances between groups to understand subgroup differences wrt fairness?"*

We will calculate SHAP values on the test set and aggregate the absolute SHAP values by sensitive group (e.g., IMD Band or Highest Education). This helps us understand if the model relies on different signals for different demographic groups, which could explain why the False Negative Rate (FNR) differs.
"""

def subgroup_shap_comparison(pipe, test_df, sensitive_attr, stage_name, model_name, sample_size=1000):
    if not SHAP_AVAILABLE:
        print("SHAP not available.")
        return

    model = pipe.named_steps["model"]
    if not hasattr(model, "feature_importances_"):
        print("Model is not tree-based.")
        return

    # 1. Sample the test set keeping the sensitive attribute
    X_test_raw, _ = get_xy(test_df)
    n = min(sample_size, len(X_test_raw))

    # Keep track of indices to align sensitive attribute later
    sample_idx = test_df.sample(n=n, random_state=RANDOM_STATE).index
    X_sample_raw = X_test_raw.loc[sample_idx]
    sensitive_values = test_df.loc[sample_idx, sensitive_attr]

    # 2. Transform features and calculate SHAP
    prep = pipe.named_steps["prep"]
    X_sample_trans = prep.transform(X_sample_raw)
    feature_names = get_feature_names_from_pipeline(pipe)

    X_sample_trans_dense = X_sample_trans.toarray() if hasattr(X_sample_trans, "toarray") else X_sample_trans

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_sample_trans_dense)
    shap_positive = shap_values[1] if isinstance(shap_values, list) else shap_values
    if len(shap_positive.shape) == 3:
        shap_positive = shap_positive[:, :, 1]

    # 3. Create a DataFrame of absolute SHAP values
    shap_abs_df = pd.DataFrame(np.abs(shap_positive), columns=feature_names)
    shap_abs_df[sensitive_attr] = sensitive_values.values

    # 4. Group by sensitive attribute to find Mean Absolute SHAP
    grouped_shap = shap_abs_df.groupby(sensitive_attr).mean().T

    # Plot top 15 overall features and how their importance varies across groups
    overall_mean = shap_abs_df.drop(columns=[sensitive_attr]).mean().sort_values(ascending=False)
    top_features = overall_mean.head(10).index

    plot_data = grouped_shap.loc[top_features]

    # Plotting
    ax = plot_data.plot(kind='bar', figsize=(12, 6), width=0.8)
    plt.title(f'Top 10 Feature Importance (Mean |SHAP|) by {sensitive_attr}\nStage: {stage_name} | Model: {model_name}')
    plt.ylabel('Mean |SHAP Value|')
    plt.xlabel('Features')
    plt.xticks(rotation=45, ha='right')
    plt.legend(title=sensitive_attr, bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

# Check if models_early is defined (requires previous cells to be run)
if "models_early" in globals() and "RandomForest" in models_early:
    print("\n--- Subgroup SHAP by Highest Education ---")
    subgroup_shap_comparison(models_early["RandomForest"], early_test, "highest_education", "early_25pct", "RandomForest")

    print("\n--- Subgroup SHAP by IMD Band ---")
    subgroup_shap_comparison(models_early["RandomForest"], early_test, "imd_band", "early_25pct", "RandomForest")
else:
    print("The preceding cells (specifically model training) must be executed before running this analysis.")

"""### Permutation Feature Importance (PFI)
Addressing the teacher's suggestion to use alternative feature importance methods like PFI. Permutation Feature Importance measures the decrease in a model score when a single feature value is randomly shuffled. This helps validate our SHAP findings using a model-agnostic approach on the test set.
"""

from sklearn.inspection import permutation_importance
import seaborn as sns

def run_permutation_importance(pipe, test_df, stage_name, model_name):
    print(f"\nCalculating Permutation Feature Importance (PFI) for {model_name} at {stage_name}...")
    X_test, y_test = get_xy(test_df)

    # Calculate PFI using balanced accuracy as the scoring metric
    result = permutation_importance(
        pipe, X_test, y_test, n_repeats=5, random_state=RANDOM_STATE, n_jobs=-1, scoring='balanced_accuracy'
    )

    # Format results
    pfi_df = pd.DataFrame({
        'feature': X_test.columns,
        'importance_mean': result.importances_mean,
        'importance_std': result.importances_std
    }).sort_values('importance_mean', ascending=False)

    # Plot Top 15 features
    top_pfi = pfi_df.head(15)

    plt.figure(figsize=(10, 6))
    sns.barplot(x='importance_mean', y='feature', data=top_pfi, color='skyblue', xerr=top_pfi['importance_std'])
    plt.title(f'Permutation Feature Importance (PFI) - Top 15\n{model_name} | Stage: {stage_name}')
    plt.xlabel('Mean Decrease in Balanced Accuracy')
    plt.ylabel('Feature')
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"pfi_{stage_name}_{model_name}.png", dpi=200)
    plt.show()

    return pfi_df

# Run PFI for the chosen model in early and full stages
if "models_early" in globals() and CHOSEN_MODEL in models_early:
    pfi_early = run_permutation_importance(models_early[CHOSEN_MODEL], early_test, "early_25pct", CHOSEN_MODEL)
    pfi_full = run_permutation_importance(models_full[CHOSEN_MODEL], full_test, "full_100pct", CHOSEN_MODEL)
else:
    print("Please run the model training cells first to define 'models_early'.")

"""### Partial Dependence Plots (PDP)
To fully address the inclusion of alternative explainability methods, Partial Dependence Plots (PDP) are generated below. PDPs illustrate the marginal effect of one or two features on the predicted outcome, providing insight into the relationship between the target and the features (e.g., whether the relationship is linear, monotonic, or more complex).
"""

from sklearn.inspection import PartialDependenceDisplay
import matplotlib.pyplot as plt

def run_partial_dependence(pipe, test_df, stage_name, model_name, features_to_plot):
    print(f"\nGenerating Partial Dependence Plots (PDP) for {model_name} at {stage_name}...")
    X_test, _ = get_xy(test_df)

    fig, ax = plt.subplots(figsize=(12, 6))
    try:
        # sklearn's PartialDependenceDisplay natively supports pipelines
        display = PartialDependenceDisplay.from_estimator(
            pipe,
            X_test,
            features_to_plot,
            kind='average',
            n_jobs=-1,
            ax=ax,
            grid_resolution=30
        )
        plt.suptitle(f"Partial Dependence Plots: {model_name} ({stage_name})", fontsize=14)
        plt.tight_layout()
        plt.savefig(OUTPUT_DIR / f"pdp_{stage_name}_{model_name}.png", dpi=200)
        plt.show()
    except Exception as e:
        print(f"Error generating PDP: {e}")

# Run PDP for the chosen model in early and full stages using key features
if "models_early" in globals() and CHOSEN_MODEL in models_early:
    # Selected features to explore (must exist in the original DataFrame)
    pdp_features = ['vle_total_clicks', 'vle_active_days', 'studied_credits']

    valid_features_early = [f for f in pdp_features if f in early_test.columns]
    if valid_features_early:
        run_partial_dependence(models_early[CHOSEN_MODEL], early_test, "early_25pct", CHOSEN_MODEL, valid_features_early)

    valid_features_full = [f for f in pdp_features if f in full_test.columns]
    if valid_features_full:
        run_partial_dependence(models_full[CHOSEN_MODEL], full_test, "full_100pct", CHOSEN_MODEL, valid_features_full)
else:
    print("The model training cells must be executed first to define 'models_early'.")

import shutil
import os

try:
    from google.colab import files

    # Use OUTPUT_DIR if it exists in the environment, otherwise default to a reasonable guess
    source_dir = str(OUTPUT_DIR) if 'OUTPUT_DIR' in globals() else '/content/oulad_outputs'
    zip_filename = 'oulad_outputs_archive'

    if not os.path.exists(source_dir):
        print(f"Error: The directory '{source_dir}' does not exist. Please re-run the cells that generate outputs.")
    else:
        print(f"Zipping the output directory: {source_dir} ...")
        shutil.make_archive(zip_filename, 'zip', source_dir)

        print("Triggering download to your local machine...")
        files.download(f"{zip_filename}.zip")
except ImportError:
    print("google.colab.files is not available in this environment.")
except Exception as e:
    print(f"An error occurred during zipping or downloading: {e}")

